# Generated by Django 4.1.7 on 2023-03-07 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notelogic', '0002_remove_note_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='note',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
