# Generated by Django 4.1.7 on 2023-03-07 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notelogic', '0003_note_cover_image_note_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='media/images/'),
        ),
    ]
